#include <furry.h>

/* generated by fbt from .png files in images folder */
#include <@FBT_APPID@_icons.h>

int32_t @FBT_APPID@_app(void* p) {
    UNUSED(p);
    FURRY_LOG_I("TEST", "Hello world");
    FURRY_LOG_I("TEST", "I'm @FBT_APPID@!");

    return 0;
}
